# Generated by Django 3.0.7 on 2020-06-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Description',
            new_name='content',
        ),
    ]
