# Generated by Django 3.0.7 on 2020-06-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200603_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='model_type',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
