# Generated by Django 3.0.7 on 2020-06-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_data_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
