# Generated by Django 3.0.7 on 2020-06-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_data_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file',
        ),
        migrations.AddField(
            model_name='data',
            name='file_type',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
